// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class ContactPerson
    {
        public int Id { get; set; }
        public string ContactpersonName { get; set; }
        public string ContactpersonTitle { get; set; }
        public string ContactpersonPhone { get; set; }
        public string ContactpersonEmail { get; set; }
        public int? CompanyId { get; set; }
        public bool? ContactpersonOnline { get; set; }
    }
}