// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class Customers
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerRegion { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerBirthDate { get; set; }
        public string CustomerGender { get; set; }
        public string CustomerCreatTimestamp { get; set; }
        public string CustomerUpdateTimestamp { get; set; }
    }
}