// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class Details
    {
        public int DetailsId { get; set; }
        public string Eventtime { get; set; }
        public string EventId { get; set; }
        public string State { get; set; }
        public string Reason { get; set; }
    }
}