// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class EventCollect
    {
        public int Id { get; set; }
        public int? EventId { get; set; }
        public int? CustomerId { get; set; }
    }
}