// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class EventLocation
    {
        public int EventLocationId { get; set; }
        public string EventLocationName { get; set; }
        public string EventLocationImage { get; set; }
        public string EventLocationInfo { get; set; }
        public string EventLocationAddress { get; set; }
        public bool? EventLocationIsstate { get; set; }
    }
}