// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class SeatPrice
    {
        public int SeatTypeId { get; set; }
        public int? SeatPrice1 { get; set; }
    }
}