// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class Administrators
    {
        public int AdministratorId { get; set; }
        public string AdministratorAccount { get; set; }
        public string AdministratorPassword { get; set; }
        public string AdministratorCreatTimestamp { get; set; }
        public string AdministratorUpdateTimestamp { get; set; }
    }
}