// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class Announcement
    {
        public int Aid { get; set; }
        public string AnnouncementType { get; set; }
        public string ContentTitle { get; set; }
        public string ContentTime { get; set; }
        public string Content { get; set; }
        public string DetailsId { get; set; }
    }
}