// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Young_Artist_Server.Models
{
    public partial class OrderMain
    {
        public int Id { get; set; }
        public int? ShoppingId { get; set; }
        public int? OrderForm { get; set; }
        public int? MemberId { get; set; }
    }
}